In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
train_df=pd.read_csv("/kaggle/input/gdsc-hics-machinelearning-hackathon/train.csv").set_index("p_id")
test_df=pd.read_csv("/kaggle/input/gdsc-hics-machinelearning-hackathon/test.csv").set_index("p_id")

In [3]:
train_df.head(10)

no_times_pregnant  glucose_concentration  blood_pressure  \
p_id                                                             
646                   2                  157.0              74   
75                    1                   79.0              75   
664                   9                  145.0              80   
333                   1                  180.0               0   
575                   1                  143.0              86   
239                   9                  164.0              84   
475                   4                  114.0              64   
17                    0                  118.0              84   
550                   4                  189.0             110   
253                   2                   90.0              80   

      skin_fold_thickness serum_insulin   bmi  diabetes pedigree  age  \
p_id                                                                    
646                    35             ?  39.4              0.134   30   
75                     30             0  32.0              0.396   22   
664                    46           130  37.9              0.637   40   
333                     0             0  43.3              0.282   41   
575                    30           330  30.1              0.892   23   
239                    21             0  30.8              0.831   32   
475                     0             0  28.9              0.126   24   
17                     47           230  45.8              0.551   31   
550                    31             0  28.5              0.680   37   
253                    14            55  24.4              0.249   24   

      diabetes  
p_id            
646          0  
75           0  
664          1  
333          1  
575          0  
239          1  
475          0  
17           1  
550          0  
253          0

In [4]:
columns=list(train_df.columns)
print(columns)

['no_times_pregnant', 'glucose_concentration', 'blood_pressure', 'skin_fold_thickness', 'serum_insulin', 'bmi', 'diabetes pedigree', 'age', 'diabetes']


In [5]:
train_df.shape

(500, 9)

In [6]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 500 entries, 646 to 260
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   no_times_pregnant      500 non-null    int64  
 1   glucose_concentration  495 non-null    float64
 2   blood_pressure         500 non-null    int64  
 3   skin_fold_thickness    500 non-null    int64  
 4   serum_insulin          500 non-null    object 
 5   bmi                    500 non-null    float64
 6   diabetes pedigree      500 non-null    float64
 7   age                    500 non-null    int64  
 8   diabetes               500 non-null    int64  
dtypes: float64(3), int64(5), object(1)
memory usage: 39.1+ KB


In [7]:
train_df.describe()

no_times_pregnant  glucose_concentration  blood_pressure  \
count         500.000000             495.000000      500.000000   
mean            3.878000             121.638384       69.854000   
std             3.424408              31.189257       19.368504   
min             0.000000               0.000000        0.000000   
25%             1.000000             100.000000       64.000000   
50%             3.000000             118.000000       72.000000   
75%             6.000000             140.500000       80.000000   
max            15.000000             199.000000      122.000000   

       skin_fold_thickness         bmi  diabetes pedigree         age  \
count           500.000000  500.000000         500.000000  500.000000   
mean             20.524000   32.293600           0.466352   33.362000   
std              16.091591    7.827558           0.329595   11.638293   
min               0.000000    0.000000           0.078000   21.000000   
25%               0.000000   27.400000           0.238000   24.000000   
50%              23.000000   32.400000           0.364500   29.000000   
75%              32.250000   36.825000           0.605000   41.000000   
max              99.000000   57.300000           2.329000   81.000000   

         diabetes  
count  500.000000  
mean     0.352000  
std      0.478072  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

In [8]:
train_df.isnull().sum()

no_times_pregnant        0
glucose_concentration    5
blood_pressure           0
skin_fold_thickness      0
serum_insulin            0
bmi                      0
diabetes pedigree        0
age                      0
diabetes                 0
dtype: int64

In [9]:
for column in train_df.columns:
    counter=0
    first=True
    name=''
    for item in train_df[column]:
        if not(str(item).isdigit()):
            if first:
                name=column
                counter+=1
                first=False
            else :
                 counter+=1
    if name :
        print("{} : {} \n".format(name,counter))

glucose_concentration : 500 

serum_insulin : 9 

bmi : 500 

diabetes pedigree : 500 



In [10]:
train_df.dtypes

no_times_pregnant          int64
glucose_concentration    float64
blood_pressure             int64
skin_fold_thickness        int64
serum_insulin             object
bmi                      float64
diabetes pedigree        float64
age                        int64
diabetes                   int64
dtype: object

In [11]:
train_df=train_df.apply(pd.to_numeric, errors='coerce')


In [12]:
train_df.dtypes

no_times_pregnant          int64
glucose_concentration    float64
blood_pressure             int64
skin_fold_thickness        int64
serum_insulin            float64
bmi                      float64
diabetes pedigree        float64
age                        int64
diabetes                   int64
dtype: object

In [13]:
for column in train_df.columns:
    train_df[column]=pd.to_numeric(train_df[column],downcast="float")

In [14]:
train_df.dtypes

no_times_pregnant        float32
glucose_concentration    float32
blood_pressure           float32
skin_fold_thickness      float32
serum_insulin            float32
bmi                      float32
diabetes pedigree        float32
age                      float32
diabetes                 float32
dtype: object

In [15]:
for column in train_df.columns:
    counter=0
    first=True
    name=''
    for item in train_df[column]:
        if not( isinstance(item, float)):
            if first:
                name=column
                counter+=1
                first=False
            else :
                 counter+=1
    if name :
        print("{} : {} \n".format(name,counter))

In [16]:
train_df.isnull().sum()

no_times_pregnant        0
glucose_concentration    5
blood_pressure           0
skin_fold_thickness      0
serum_insulin            9
bmi                      0
diabetes pedigree        0
age                      0
diabetes                 0
dtype: int64

In [17]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
train_df=pd.DataFrame(imp_mean.fit_transform(train_df))

In [18]:
train_df.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
7    0
8    0
dtype: int64

In [19]:
X_train=np.array(train_df.iloc[:,:-1])
y_train=np.array(train_df.iloc[:,-1:])

In [20]:
X_train.shape

(500, 8)

In [21]:
y_train.shape

(500, 1)

In [22]:
model = tf.keras.Sequential([
                tf.keras.layers.Dense(16,activation = tf.nn.relu),
                tf.keras.layers.Dense(12,activation = tf.nn.relu),                          
                tf.keras.layers.Dense(8,activation = tf.nn.relu),
                tf.keras.layers.Dense(1,activation = tf.nn.sigmoid)]
)


User settings:

   KMP_AFFINITY=granularity=fine,verbose,compact,1,0
   KMP_BLOCKTIME=0
   KMP_DUPLICATE_LIB_OK=True
   KMP_INIT_AT_FORK=FALSE
   KMP_SETTINGS=1
   KMP_WARNINGS=0

Effective settings:

   KMP_ABORT_DELAY=0
   KMP_ADAPTIVE_LOCK_PROPS='1,1024'
   KMP_ALIGN_ALLOC=64
   KMP_ALL_THREADPRIVATE=128
   KMP_ATOMIC_MODE=2
   KMP_BLOCKTIME=0
   KMP_CPUINFO_FILE: value is not defined
   KMP_DETERMINISTIC_REDUCTION=false
   KMP_DEVICE_THREAD_LIMIT=2147483647
   KMP_DISP_NUM_BUFFERS=7
   KMP_DUPLICATE_LIB_OK=true
   KMP_ENABLE_TASK_THROTTLING=true
   KMP_FORCE_REDUCTION: value is not defined
   KMP_FOREIGN_THREADS_THREADPRIVATE=true
   KMP_FORKJOIN_BARRIER='2,2'
   KMP_FORKJOIN_BARRIER_PATTERN='hyper,hyper'
   KMP_GTID_MODE=3
   KMP_HANDLE_SIGNALS=false
   KMP_HOT_TEAMS_MAX_LEVEL=1
   KMP_HOT_TEAMS_MODE=0
   KMP_INIT_AT_FORK=true
   KMP_LIBRARY=throughput
   KMP_LOCK_KIND=queuing
   KMP_MALLOC_POOL_INCR=1M
   KMP_NUM_LOCKS_IN_BLOCK=1
   KMP_PLAIN_BARRIER='2,2'
   KMP_PLAIN_BARRIER_P

In [23]:
from tensorflow.keras.optimizers import RMSprop
model.compile(optimizer=RMSprop(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics = ['accuracy'])

In [24]:
model.fit(X_train, y_train,epochs =1000,verbose=2)

2021-12-10 15:30:05.378536: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/1000
16/16 - 1s - loss: 8.3143 - accuracy: 0.6420
Epoch 2/1000
16/16 - 0s - loss: 4.2724 - accuracy: 0.6060
Epoch 3/1000
16/16 - 0s - loss: 2.2612 - accuracy: 0.5960
Epoch 4/1000
16/16 - 0s - loss: 1.2884 - accuracy: 0.5860
Epoch 5/1000
16/16 - 0s - loss: 0.9580 - accuracy: 0.6020
Epoch 6/1000
16/16 - 0s - loss: 0.7946 - accuracy: 0.6520
Epoch 7/1000
16/16 - 0s - loss: 0.7242 - accuracy: 0.6480
Epoch 8/1000
16/16 - 0s - loss: 0.6873 - accuracy: 0.6440
Epoch 9/1000
16/16 - 0s - loss: 0.6765 - accuracy: 0.6880
Epoch 10/1000
16/16 - 0s - loss: 0.6527 - accuracy: 0.6620
Epoch 11/1000
16/16 - 0s - loss: 0.6424 - accuracy: 0.7020
Epoch 12/1000
16/16 - 0s - loss: 0.6267 - accuracy: 0.6820
Epoch 13/1000
16/16 - 0s - loss: 0.6258 - accuracy: 0.6740
Epoch 14/1000
16/16 - 0s - loss: 0.6215 - accuracy: 0.6700
Epoch 15/1000
16/16 - 0s - loss: 0.6210 - accuracy: 0.6860
Epoch 16/1000
16/16 - 0s - loss: 0.6109 - accuracy: 0.6800
Epoch 17/1000
16/16 - 0s - loss: 0.6034 - accuracy: 0.6920
Epoch 

In [25]:
X_test=np.array(test_df)

In [26]:
X_test.shape 

(267, 8)

In [27]:
predictions=model.predict(X_test)

In [28]:
predictions=list(predictions)

In [29]:
predictions

[array([0.9952222], dtype=float32),
 array([0.95692444], dtype=float32),
 array([0.9681965], dtype=float32),
 array([0.31104815], dtype=float32),
 array([0.1904037], dtype=float32),
 array([0.01816359], dtype=float32),
 array([0.94401485], dtype=float32),
 array([0.2079609], dtype=float32),
 array([0.05985236], dtype=float32),
 array([0.37709752], dtype=float32),
 array([0.50542647], dtype=float32),
 array([5.262548e-05], dtype=float32),
 array([0.8376976], dtype=float32),
 array([0.96353984], dtype=float32),
 array([0.1087082], dtype=float32),
 array([0.79729044], dtype=float32),
 array([0.28368238], dtype=float32),
 array([0.11569652], dtype=float32),
 array([0.9546639], dtype=float32),
 array([0.03256074], dtype=float32),
 array([0.06043637], dtype=float32),
 array([0.26818323], dtype=float32),
 array([0.04493585], dtype=float32),
 array([0.8511306], dtype=float32),
 array([0.94158614], dtype=float32),
 array([0.82754433], dtype=float32),
 array([0.00073016], dtype=float32),
 array(

In [30]:
for i in range(len(predictions)):
    if predictions[i]>0.7:
        predictions[i]=1
    else :
        predictions[i]=0

In [31]:
predictions

[1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [32]:
ids=test_df.index

In [33]:
output=pd.DataFrame({'p_id':ids,'diabetes':predictions})
output.to_csv('submission.csv', index=False)